### ISSUE TITLE
Bug with maybe malformated file 

### ISSUE THREAD

**Issue by yodatak** [IceWreck/tagpatch#2]
Do you want to continue? [y/N]: y
  [------------------------------------]    1%  00:03:33
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 184, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 155, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/id3/_file.py", line 169, in load
    data = read_full(fileobj, self.size - 10)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 656, in read_full
    raise IOError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/bin/tagpatch", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/__main__.py", line 82, in main
    cli()
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/options.py", line 17, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/options.py", line 31, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/options.py", line 46, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/options.py", line 61, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/__main__.py", line 76, in embed_lrc
    patch.apply()
  File "/root/.local/lib/python3.12/site-packages/tagpatch/patches/embed_lrc.py", line 76, in apply
    f: mutagen.FileType = music_tag.load_file(dst_file)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_tag/__init__.py", line 55, in load_file
    mfile = mutagen.File(filename, easy=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 163, in wrapper_func
    return func(h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_file.py", line 300, in File
    return Kind(fileobj, filename=filething.filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_file.py", line 47, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 155, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/id3/_file.py", line 408, in load
    self.tags = ID3(fileobj, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/id3/_file.py", line 76, in __init__
    super(ID3, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/mutagen/id3/_tags.py", line 172, in __init__
    super(ID3Tags, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 533, in __init__
    super(DictProxy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/mutagen/_tags.py", line 110, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 188, in wrapper
    reraise(exc_dest, err, sys.exc_info()[2])
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 42, in reraise
    raise tp(value).with_traceback(tb)
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 184, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 155, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/id3/_file.py", line 169, in load
    data = read_full(fileobj, self.size - 10)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 656, in read_full
    raise IOError
mutagen.id3._util.error

The mass modification crash maybe because of a bad file cannot do the whole folder what can i do ?

**Comment by yodatak** [comment]
some more exemple

Do you want to continue? [y/N]: y
  [###---------------------------------]    9%  00:00:16
Traceback (most recent call last):
  File "/root/.local/bin/tagpatch", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/__main__.py", line 82, in main
    cli()
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/options.py", line 17, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/options.py", line 31, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/options.py", line 46, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/options.py", line 61, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/tagpatch/__main__.py", line 76, in embed_lrc
    patch.apply()
  File "/root/.local/lib/python3.12/site-packages/tagpatch/patches/embed_lrc.py", line 76, in apply
    f: mutagen.FileType = music_tag.load_file(dst_file)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_tag/__init__.py", line 55, in load_file
    mfile = mutagen.File(filename, easy=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 163, in wrapper_func
    return func(h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_file.py", line 300, in File
    return Kind(fileobj, filename=filething.filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_file.py", line 47, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 155, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/id3/_file.py", line 420, in load
    self.info = self._Info(fileobj, offset)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/_util.py", line 184, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mutagen/mp3/__init__.py", line 401, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame

**Comment by IceWreck** [comment]
huh, ill take a look this weekend

**Comment by IceWreck** [comment]
Could you try updating it to the latest version ?
